### ISSUE TITLE
Crash when moving frames 

### ISSUE THREAD

**Issue by AndreiTS** [rwtema/FunkyLocomotion#106]
[16:32:34] [Server thread/ERROR]: A TileEntity type codechicken.multipart.handler.MultipartSaveLoad$TileNBTContainer has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class codechicken.multipart.handler.MultipartSaveLoad$TileNBTContainer is missing a mapping! This is a bug!
	at net.minecraft.tileentity.TileEntity.func_189516_d(TileEntity.java:81) ~[aqk.class:?]
	at net.minecraft.tileentity.TileEntity.func_189515_b(TileEntity.java:72) ~[aqk.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:384) [atj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:175) [atj.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:199) [lr.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:227) [lr.class:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1013) [ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:355) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71267_a(IntegratedServer.java:325) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:393) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71260_j(IntegratedServer.java:456) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
[16:32:34] [Server thread/ERROR]: A TileEntity type codechicken.multipart.handler.MultipartSaveLoad$TileNBTContainer has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class codechicken.multipart.handler.MultipartSaveLoad$TileNBTContainer is missing a mapping! This is a bug!
	at net.minecraft.tileentity.TileEntity.func_189516_d(TileEntity.java:81) ~[aqk.class:?]
	at net.minecraft.tileentity.TileEntity.func_189515_b(TileEntity.java:72) ~[aqk.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:384) [atj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:175) [atj.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:199) [lr.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:227) [lr.class:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1013) [ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:355) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71267_a(IntegratedServer.java:325) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:393) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71260_j(IntegratedServer.java:456) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]

**Comment by NerdCraft** [comment]
another one: http://pastebin.com/Lw1d0yJk

**Comment by bit2shift** [comment]
You're using a mix of new and old mods.
Remove these and all the mods that weren't made for 1.10.2, then try again:
- Aroma1997Core-1.9.4-1.1.1.1.jar
- Aroma1997s-Dimensional-World-1.9.4-1.2.0.6.jar
- AromaBackup-1.9.4-1.0.1.1.jar
- hopperducts-mc1.9.4-1.4.8.jar
- netherportalfix-mc1.9.4-4.0.1.jar
- redstonepaste-mc1.9.4-1.7.4.jar
- refinedstorage-1.2.23.jar
