### ISSUE TITLE
NullPointerException whenever frame is moved.

### ISSUE THREAD

**Issue by aionys** [rwtema/FunkyLocomotion#121]
There's no crash, and it doesn't seem to have any negative effects other than the repeated error report in the log, but any time the frame in my game moves, the following error occurs.

In truth, I'm only reporting it because the error tells me to.

```
[19:55:02] [Server thread/ERROR] [FML]: A TileEntity funkylocomotion:tilePusher(com.rwtema.funkylocomotion.blocks.TilePusher) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.NullPointerException
        at com.rwtema.funkylocomotion.blocks.TilePusher.func_145839_a(TilePusher.java:56) ~[TilePusher.class:?]
        at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:123) [aqk.class:?]
        at com.rwtema.funkylocomotion.factory.DefaultMoveFactory.loadTile(DefaultMoveFactory.java:89) [DefaultMoveFactory.class:?]
        at com.rwtema.funkylocomotion.factory.DefaultMoveFactory.recreateBlock(DefaultMoveFactory.java:77) [DefaultMoveFactory.class:?]
        at com.rwtema.funkylocomotion.movers.MoveManager.finishMoving(MoveManager.java:422) [MoveManager.class:?]
        at com.rwtema.funkylocomotion.movers.MoverEventHandler.onPostWorldTick(MoverEventHandler.java:49) [MoverEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_515_MoverEventHandler_onPostWorldTick_WorldTickEvent.invoke(.dynamic) [?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:269) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:718) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
```

**Comment by aionys** [comment]
Sorry, it's version alpha-0.0.3
