### ISSUE TITLE
[1.12] Non-host players kicked from LAN whenever a frame is moved

### ISSUE THREAD

**Issue by Renniuq** [rwtema/FunkyLocomotion#126]
While it seems somewhat similar to #101 in outward appearance, it doesn't give any error on the client end, simply saying "disconnected" on the screen when kicked, and the console doesn't give any errors or reasons for the disconnection, which is unusual.

As for the host, they stay connected the whole time, have no issues, but their console gives the following error when the other player (me) gets kicked:

`NetworkDispatcher exception
io.netty.handler.codec.EncoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:544)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296)
	at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:245)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1408)
	at io.netty.buffer.UnpooledHeapByteBuf.capacity(UnpooledHeapByteBuf.java:114)
	at io.netty.buffer.DuplicatedByteBuf.capacity(DuplicatedByteBuf.java:84)
	at net.minecraft.network.PacketBuffer.capacity(PacketBuffer.java:434)
	at io.netty.buffer.UnsafeByteBufUtil.setBytes(UnsafeByteBufUtil.java:546)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:260)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1069)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1060)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1050)
	at net.minecraft.network.PacketBuffer.writeBytes(PacketBuffer.java:1094)
	at net.minecraft.network.play.server.SPacketCustomPayload.func_148840_b(SPacketCustomPayload.java:51)
	at net.minecraft.network.NettyPacketEncoder.encode(NettyPacketEncoder.java:51)
	at net.minecraft.network.NettyPacketEncoder.encode(NettyPacketEncoder.java:12)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
	... 18 more
14:50:39	FML	NetworkDispatcher exception
io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1408)
	at io.netty.buffer.UnpooledHeapByteBuf.array(UnpooledHeapByteBuf.java:154)
	at net.minecraft.network.PacketBuffer.array(PacketBuffer.java:1264)
	at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.toS3FPackets(FMLProxyPacket.java:151)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:538)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296)
	at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:245)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)`

it repeats that last stacktrace 4 more times, but they are identical to that one. I can't find anything in the log linking this to Funky Locomotion, but based on the fact that it happens with 100% consistency and reliability, and only when moving frames, I assume there's a connection. The only blocks they are moving though are the frames and some chisel obsidian.

**Comment by smithb99** [comment]
Reproducible on my client, same exact issue.  This happens regardless of what the motor type is (pusher, puller, etc.) or what it's pushing.  My friend about killed me when I kept kicking him on accident, so I hope this gets fixed soon.

Minecraft 1.12
Java 1.8.0_25
Forge 14.23.3.2655
Windows 10 Pro

**Comment by monkeybee11** [comment]
im geting the smae problem as well
my dad keeps getting kicked fomr my lan world when ever a frame is moved

minecraft 1.12.2
java (dont know 1.8 something)
forge 1423.4.2745
win10 pro
(all these numbers are the same for my dads computer)

**Comment by ghost** [comment]
Reporting same issue as of December 2018
Forge 14.23.5.2775
Java 1.8.0_191
MC 1.12.2
Win 10 Pro

**Comment by ghost** [comment]
I really hope this issue gets fixed. Friends and I play on a LAN server and there's so much potential with this mod.

**Comment by erwin1234777** [comment]
Same here, 1.12.2 forge 2847
latest version 1.1.2

**Comment by KFYakusa** [comment]
same here, MC: 1.12.2, 
forge: 14.23.5,
