### ISSUE TITLE
Game crashes on riding facades attacthed to moving Slider Frames

### ISSUE THREAD

**Issue by HonestyK** [rwtema/FunkyLocomotion#128]
I built a moving platform using Slider Frames to move some facades and the game crashes consistently when I try and stand on the moving parts.

funky-locomotion-1.12.2-1.1.1

**Comment by altDark** [comment]
Hi,
I have the same issue in "funky-locomotion-1.12.2-1.1.1". The same platform works well wiht "funky-locomotion-1.12.2-1.1.0.jar".
Error is:
Description: Ticking block entity
java.lang.NoSuchFieldError: isCollidedHorizontally
	at com.rwtema.funkylocomotion.EntityMovingEventHandler.moveEntity(EntityMovingEventHandler.java:206)
	at com.rwtema.funkylocomotion.blocks.TileMovingBase.func_73660_a(TileMovingBase.java:190)
	at com.rwtema.funkylocomotion.blocks.TileMovingServer.func_73660_a(TileMovingServer.java:68)
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
Head --
Thread: Server thread
Stacktrace:
		at com.rwtema.funkylocomotion.EntityMovingEventHandler.moveEntity(EntityMovingEventHandler.java:206)
	
	at com.rwtema.funkylocomotion.blocks.TileMovingBase.func_73660_a(TileMovingBase.java:190)
	
	at com.rwtema.funkylocomotion.blocks.TileMovingServer.func_73660_a(TileMovingServer.java:68)
-- Block entity being ticked 
--
Details:
	Name: funkylocomotion:tile_mover 
// com.rwtema.funkylocomotion.blocks.TileMovingServer
	Block type: ID #2869 (tile.null 
// com.rwtema.funkylocomotion.blocks.BlockMoving)
	Block data value: 0 / 0x0 / 0b0000
	
Block location: World: (-237,75,-1659), 
Chunk: (at 3,4,5 in -15,-104; contains blocks -240,0,-1664 to -225,255,-1649), 
Region: (-1,-4; contains chunks -32,-128 to -1,-97, blocks -512,0,-2048 to -1,255,-1537)
	
Actual block type: ID #2869 (tile.null // com.rwtema.funkylocomotion.blocks.BlockMoving)
	
Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
