### ISSUE TITLE
CME with Thermal Dynamics

### ISSUE THREAD

**Issue by Bitterholz** [rwtema/FunkyLocomotion#49]
java.util.ConcurrentModificationException
	at java.util.LinkedList$ListItr.checkForComodification(Unknown Source)
	at java.util.LinkedList$ListItr.remove(Unknown Source)
	at cofh.thermaldynamics.multiblock.MultiBlockGridWithRoutes.doTickProcessing(MultiBlockGridWithRoutes.java:21)
	at cofh.thermaldynamics.core.WorldGridList.tickEnd(WorldGridList.java:72)
	at cofh.thermaldynamics.core.TickHandler.tick(TickHandler.java:85)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_481_TickHandler_tick_WorldTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:255)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:645)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by nitsuga5124** [comment]
report it here https://github.com/CoFH/Feedback/issues
