### ISSUE TITLE
Repeating Crash

### ISSUE THREAD

**Issue by cjburkey01** [rwtema/FunkyLocomotion#82]
So, I built a frame quarry in my world, and every time I leave the chunks, it crashes because the chunk loader doesn't work as it moves, so it unsets the blocks and Funky Locomotion doesn't seem to like that.

Here's the error: http://pastebin.com/7DUBbve4

**Comment by sci4me** [comment]
I also have this: http://pastebin.com/pPPa5sJU

**Comment by decryptedchaos** [comment]
this bug is driving me crazy,   I'm so disappointed that i cant build a frame quarry because of this bug..   

i even tried working around it with two chunk loaders  one on the main sled,  and another on a secondary sled moving 0.55 sec after the first one so that one chunk loader was always stationary at any given time still causes a server crash loop which can only be recovered by disabling the mod and letting it remove all the blocks.   


Furthermore,   frankly this should be considered one of the top most priority critical bugs,   consider from a server admin standpoint if one has a popular server,   would almost certainly have no choice but to remove this mod because as soon as someone made a frame quarry and left the chunk  boom,  the server goes into a crash loop.  which would likely happen far too often 

Its been posted many times over so no real point in this but for the sake of thoroughness here is the stack trace

	[23:59:30] [Server thread/ERROR] [FML]: Exception caught during firing event cpw.mods.fml.common.gameevent.TickEvent$WorldTickEvent@209a353b:

	java.lang.NullPointerException

		at com.rwtema.funkylocomotion.movers.MoveManager.startMoving(MoveManager.java:239) ~[MoveManager.class:?]

		at com.rwtema.funkylocomotion.blocks.TilePusher.startMoving(TilePusher.java:175) ~[TilePusher.class:?]

		at com.rwtema.funkylocomotion.movers.MoverEventHandler.onPostWorldTick(MoverEventHandler.java:36) ~[MoverEventHandler.class:?]

		at cpw.mods.fml.common.eventhandler.ASMEventHandler_309_MoverEventHandler_onPostWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?]

		at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]

		at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]

		at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:255) [FMLCommonHandler.class:?]

		at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:645) [MinecraftServer.class:?]

		at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]

		at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]

		at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]

		at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

	[23:59:30] [Server thread/ERROR] [FML]: Index: 7 Listeners:

	[23:59:30] [Server thread/ERROR] [FML]: 0: NORMAL

	[23:59:30] [Server thread/ERROR] [FML]: 1: ASM: ic2.core.TickHandler@4eb8378c onWorldTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

	[23:59:30] [Server thread/ERROR] [FML]: 2: ASM: thaumcraft.common.lib.events.ServerTickEventsFML@409b271d serverWorldTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

	[23:59:30] [Server thread/ERROR] [FML]: 3: ASM: vazkii.botania.common.item.ItemGrassSeeds@1bd4df69 onTickEnd(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

	[23:59:30] [Server thread/ERROR] [FML]: 4: ASM: vazkii.botania.common.item.equipment.tool.terrasteel.ItemTerraAxe@40cc4642 onTickEnd(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

	[23:59:30] [Server thread/ERROR] [FML]: 5: ASM: io.endertech.handler.WorldEventHandler@4b9e0cac onWorldTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

	[23:59:30] [Server thread/ERROR] [FML]: 6: ASM: io.endertech.multiblock.handler.MultiblockServerTickHandler@297bd56 onWorldTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

	[23:59:30] [Server thread/ERROR] [FML]: 7: ASM: com.rwtema.funkylocomotion.movers.MoverEventHandler@16e3da96 onPostWorldTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

	[23:59:30] [Server thread/ERROR] [FML]: 8: ASM: openmods.world.DelayedActionTickHandler@44a01d8e onWorldTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

	[23:59:30] [Server thread/ERROR] [FML]: 9: ASM: openmods.block.BlockDropsStore$FmlListener@53f1051e onWorldTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

	[23:59:30] [Server thread/ERROR] [FML]: 10: ASM: pneumaticCraft.common.semiblock.SemiBlockManager@74dfcb38 onWorldTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

	[23:59:30] [Server thread/ERROR] [FML]: 11: ASM: pneumaticCraft.common.HackTickHandler@46b69d35 worldTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

	[23:59:30] [Server thread/ERROR] [FML]: 12: ASM: pneumaticCraft.common.TickHandlerPneumaticCraft@723c0ae0 tickEnd(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

	[23:59:30] [Server thread/ERROR] [FML]: 13: ASM: tmechworks.lib.multiblock.MultiblockServerTickHandler@768cefa0 tick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

	[23:59:30] [Server thread/ERROR] [FML]: 14: ASM: codechicken.wirelessredstone.core.WRCoreEventHandler@7f393828 serverTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

	[23:59:30] [Server thread/ERROR] [FML]: 15: ASM: codechicken.nei.ServerHandler@30482c51 tickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

	[23:59:30] [Server thread/ERROR] [FML]: 16: ASM: erogenousbeef.bigreactors.common.BigReactorsTickHandler@48834ce7 onWorldTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

	[23:59:30] [Server thread/ERROR] [FML]: 17: ASM: erogenousbeef.core.multiblock.MultiblockServerTickHandler@715d528f onWorldTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

	[23:59:30] [Server thread/ERROR] [FML]: 18: ASM: vazkii.botania.common.core.handler.CommonTickHandler@7834f3d0 onTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

	[23:59:30] [Server thread/ERROR] [FML]: 19: ASM: codechicken.chunkloader.ChunkLoaderEventHandler@1981c0c6 worldTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

	[23:59:30] [Server thread/ERROR] [FML]: 20: ASM: morph.common.core.TickHandlerServer@1009551e worldTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

	[23:59:30] [Server thread/ERROR] [FML]: 21: ASM: portalgun.common.core.TickHandlerServer@2091513a onWorldTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

	[23:59:30] [Server thread/ERROR] [FML]: 22: ASM: cofh.thermaldynamics.core.TickHandler@c2efb5c tick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

	[23:59:30] [Server thread/ERROR] [FML]: 23: ASM: codechicken.wirelessredstone.addons.WRAddonEventHandler@4e1b3322 worldTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

	[23:59:30] [Server thread/ERROR] [FML]: 24: ASM: forestry.core.TickHandlerCoreServer@3c7e4a92 onWorldTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

	[23:59:30] [Server thread/ERROR] [FML]: 25: ASM: codechicken.lib.world.WorldExtensionManager$WorldExtensionEventHandler@6d98cf00 serverTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

	[23:59:30] [Server thread/ERROR] [FML]: 26: ASM: mrtjp.core.world.BlockUpdateHandler$@7ee6b51b onTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

	[23:59:30] [Server thread/ERROR] [FML]: 27: ASM: net.quetzi.morpheus.MorpheusEventHandler@2ff69e13 worldTickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

	[23:59:30] [Server thread/ERROR] [FML]: 28: ASM: buildcraft.robotics.map.MapManager@f6650f7 tickDelayedWorlds(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

	[23:59:30] [Server thread/ERROR] [FML]: 29: ASM: buildcraft.transport.stripes.PipeExtensionListener@668de52 tick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V

	[23:59:30] [Server thread/ERROR] [FML]: 30: ASM: vazkii.botania.common.block.BlockPistonRelay@3f26f70d tickEnd(Lcpw/mods/fml/common/gameevent/TickEvent;)V

	[23:59:30] [Server thread/ERROR] [FML]: 31: ASM: appeng.hooks.TickHandler@29a73dc7 onTick(Lcpw/mods/fml/common/gameevent/TickEvent;)V

	[23:59:30] [Server thread/ERROR]: Encountered an unexpected exception

	java.lang.NullPointerException

		at com.rwtema.funkylocomotion.movers.MoveManager.startMoving(MoveManager.java:239) ~[MoveManager.class:?]

		at com.rwtema.funkylocomotion.blocks.TilePusher.startMoving(TilePusher.java:175) ~[TilePusher.class:?]

		at com.rwtema.funkylocomotion.movers.MoverEventHandler.onPostWorldTick(MoverEventHandler.java:36) ~[MoverEventHandler.class:?]

		at cpw.mods.fml.common.eventhandler.ASMEventHandler_309_MoverEventHandler_onPostWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?]

		at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]

		at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]

		at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:255) ~[FMLCommonHandler.class:?]

		at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:645) ~[MinecraftServer.class:?]

		at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]

		at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]

		at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]

		at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

**Comment by cjburkey01** [comment]
Set the side platform to something like 2 seconds, it takes a second to a second and a half to move the frames.  This issue is caused by the chunkloader being disabled when it starts moving, meaning the blocks unload.  Once the chunkloader has stopped moving, it works again.
